version: 2
project_name: snapman

builds:
  - id: snapman-linux
    main: ./cmd/snapman
    binary: snapman
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: snapman-linux-archive
    builds:
      - snapman-linux
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_{{ .Arch }}"

checksum:
  name_template: checksums.txt
