name: snapman
base: core22
version: git
summary: Clean up disabled Snap revisions to reclaim disk space
license: MIT
confinement: classic
grade: stable

contact: https://github.com/ersinakyuz/snapman/issues
issues: https://github.com/ersinakyuz/snapman/issues
source-code: https://github.com/ersinakyuz/snapman
website: https://github.com/ersinakyuz/snapman

description: |
  SnapMan is a lightweight CLI tool that safely cleans up disabled
  Snap revisions and helps reclaim disk space on Ubuntu systems.

  It scans snap list --all output, verifies revision files on disk,
  and can remove only the disabled revisions after confirmation.

apps:
  snapman:
    command: snapman

parts:
  snapman:
    plugin: go
    source: .
    build-snaps:
      - go/1.20/stable
    build-packages:
      - git
    go-channel: 1.20/stable
    override-build: |
      set -eux
      snapcraftctl build
